# Site settings
title: Mohsen Ahmadi
description: >- # this means to ignore newlines until "baseurl:"
  Agile Product/Project Manager and Scrum Master
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: ahmadipm/ahmadipm.github.io

remote_theme: YoussefRaafatNasry/portfolYOU@v2.2.2

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Mohsen Ahmadi
  image    : ""
  email    : mohsen@ahmadi.pm
  github   : ahmadipm
  twitter  : ahmadi_pm
  linkedin : mohsenahmadi
  facebook : mohsenahmadii


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock